# Generated by Django 5.0.6 on 2024-05-16 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_alter_district_user_alter_hospital_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='field_name',
        ),
        migrations.AlterField(
            model_name='log',
            name='new_value',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='previous_value',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=201),
        ),
        migrations.CreateModel(
            name='ConflictLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.log')),
            ],
        ),
    ]
