# Generated by Django 5.0.6 on 2024-05-16 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_remove_log_field_name_alter_log_new_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.user'),
        ),
        migrations.AddField(
            model_name='refrigerator',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.user'),
        ),
    ]
